"""Compatibility facade for application startup and shutdown runtime helpers."""

from __future__ import annotations

from app.main_runtime_contracts import AppRuntimeResources
from app.main_shutdown_runtime import (
    _cancel_background_task,
    _close_checkpointer,
    _close_course_generation_pool,
    _close_neo4j,
    _close_playwright_browser,
    _close_search_pools,
    _close_shared_database_engine,
    _close_sources_pool,
    _persist_emotion_state,
    _shutdown_mcp_client,
    _stop_heartbeat,
    _stop_scheduled_executor,
    _stop_soul_bridge,
    shutdown_application,
)
from app.main_startup_runtime import (
    _bootstrap_lms_connectors,
    _discover_domain_plugins,
    _init_observability,
    _initialize_agent_registry,
    _initialize_llm_pool,
    _initialize_mcp_client,
    _initialize_unified_client,
    _log_startup_banner,
    _maybe_run_migrations,
    _prewarm_corrective_rag,
    _prewarm_multi_agent_graph,
    _prewarm_rag_agent,
    _recover_course_generation_jobs,
    _restore_runtime_policy,
    _run_startup_health_check,
    _schedule_runtime_audit,
    _start_living_agent,
    _start_magic_link_maintenance,
    _start_scheduled_executor,
    _start_soul_bridge,
    _validate_embedding_dimensions,
    _validate_neo4j,
    _validate_pgvector,
    _validate_postgresql,
    _validate_prompt_loader,
    startup_application,
)


__all__ = [
    "AppRuntimeResources",
    "startup_application",
    "shutdown_application",
    "_log_startup_banner",
    "_init_observability",
    "_validate_postgresql",
    "_validate_neo4j",
    "_validate_pgvector",
    "_validate_prompt_loader",
    "_discover_domain_plugins",
    "_maybe_run_migrations",
    "_restore_runtime_policy",
    "_bootstrap_lms_connectors",
    "_initialize_llm_pool",
    "_initialize_agent_registry",
    "_schedule_runtime_audit",
    "_initialize_unified_client",
    "_validate_embedding_dimensions",
    "_prewarm_rag_agent",
    "_prewarm_corrective_rag",
    "_prewarm_multi_agent_graph",
    "_run_startup_health_check",
    "_recover_course_generation_jobs",
    "_initialize_mcp_client",
    "_start_scheduled_executor",
    "_start_living_agent",
    "_start_soul_bridge",
    "_start_magic_link_maintenance",
    "_close_neo4j",
    "_stop_scheduled_executor",
    "_cancel_background_task",
    "_stop_heartbeat",
    "_persist_emotion_state",
    "_stop_soul_bridge",
    "_shutdown_mcp_client",
    "_close_checkpointer",
    "_close_sources_pool",
    "_close_course_generation_pool",
    "_close_search_pools",
    "_close_playwright_browser",
    "_close_shared_database_engine",
]
