[*]
wallpaper_mode=fit
wallpaper_common=1
wallpaper=/usr/share/wiii-computer/wallpaper.png
desktop_bg=#f3efe7
desktop_fg=#2f2b27
desktop_shadow=#f8f5ef
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=0
show_mounts=0
