"""
LLM Query Planner — Sprint 197: "Thông Minh Tìm Kiếm"

Pre-step before product search ReAct loop. Uses a LIGHT-tier LLM to
understand the user query, detect intent (B2B vs B2C), and generate
optimized search queries per platform — solving the Vietnamese diacritics
problem with DuckDuckGo and improving cross-language search quality.

Gate: enable_query_planner
"""

import logging
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# =============================================================================
# Models
# =============================================================================

class SearchIntent(str, Enum):
    """Classification of user's search intent."""
    B2C_CONSUMER = "B2C_CONSUMER"
    B2B_SOURCING = "B2B_SOURCING"
    PRICE_COMPARISON = "PRICE_COMPARISON"
    INTERNATIONAL = "INTERNATIONAL"
    CHINESE_SOURCING = "CHINESE_SOURCING"


class SearchStrategy(str, Enum):
    """Recommended search execution order."""
    ECOMMERCE_FIRST = "ECOMMERCE_FIRST"
    B2B_FIRST = "B2B_FIRST"
    COMPARISON_FIRST = "COMPARISON_FIRST"
    CHINA_FIRST = "CHINA_FIRST"


class SubQuery(BaseModel):
    """A single optimized search query targeted at a specific platform."""
    platform: str = Field(description="Target platform: google_shopping, shopee, dealer, international, websosanh, all_web, facebook")
    query: str = Field(description="Optimized search query string")
    language: str = Field(default="vi", description="Query language: vi, en, mixed")
    priority: int = Field(default=1, ge=1, le=3, description="Execution priority: 1=first round, 2=second, 3=verification")


class QueryPlan(BaseModel):
    """Complete search plan generated by LLM planner."""
    product_name_en: str = Field(description="Product name in English")
    product_name_vi: str = Field(description="Product name in Vietnamese")
    brand: str = Field(default="", description="Extracted brand name")
    model_number: str = Field(default="", description="Extracted model/part number")
    intent: SearchIntent = Field(default=SearchIntent.B2C_CONSUMER, description="Detected search intent")
    search_strategy: SearchStrategy = Field(default=SearchStrategy.ECOMMERCE_FIRST, description="Recommended strategy")
    sub_queries: List[SubQuery] = Field(default_factory=list, description="Optimized sub-queries per platform")
    synonyms: List[str] = Field(default_factory=list, description="Product name synonyms and variations")
    reasoning: str = Field(default="", description="Brief reasoning for the chosen strategy")


# =============================================================================
# Planner Prompt
# =============================================================================

_PLANNER_PROMPT = """Bạn là chuyên gia tối ưu hóa tìm kiếm sản phẩm. Nhiệm vụ: phân tích câu hỏi của user và tạo kế hoạch tìm kiếm tối ưu.

## QUY TẮC QUAN TRỌNG

### DuckDuckGo (dùng cho dealer, international search):
- **KHÔNG BAO GIỜ** dùng tiếng Việt có dấu (đ, ă, ê, ô, ơ, ư, á, é, ...) → DuckDuckGo sẽ trả về rác
- Dùng tiếng Anh HOẶC tiếng Việt KHÔNG DẤU cho DuckDuckGo queries
- Ví dụ: "dau in Zebra ZXP7 dai ly" (không dấu) hoặc "Zebra ZXP7 printhead dealer Vietnam"

### Google/Serper/Shopee/Lazada (dùng cho ecommerce):
- Tiếng Việt CÓ DẤU hoạt động tốt → dùng đầy đủ dấu
- Ví dụ: "đầu in máy in thẻ Zebra ZXP7 chính hãng"

### Phân loại intent:
- B2B_SOURCING: linh kiện, thiết bị công nghiệp, "đại lý", "nhà phân phối", "chính hãng", "nguồn cung"
- B2C_CONSUMER: hàng tiêu dùng bình thường (điện thoại, laptop, quần áo, ...)
- PRICE_COMPARISON: user muốn "so sánh giá", "rẻ nhất", "web nào rẻ"
- INTERNATIONAL: user muốn "giá quốc tế", "nhập khẩu", "mua từ nước ngoài"
- CHINESE_SOURCING: user muốn tìm từ "1688", "Taobao", "Trung Quốc", "hàng Trung Quốc", "nhập TQ", "AliExpress", "so sánh giá TQ"

### Chiến lược:
- B2B_SOURCING → B2B_FIRST: dealer (EN query) → international (EN) → ecommerce (VI)
- B2C_CONSUMER → ECOMMERCE_FIRST: ecommerce (VI) → websosanh → all_web
- PRICE_COMPARISON → COMPARISON_FIRST: websosanh → google_shopping → ecommerce
- INTERNATIONAL → B2B_FIRST: international (EN) → dealer (EN) → ecommerce (VI)
- CHINESE_SOURCING → CHINA_FIRST: international (EN+CN, 1688/Taobao/AliExpress) → ecommerce (VI) → dealer

### Extract:
- Tách brand + model number từ query (VD: "đầu in Zebra ZXP7" → brand="Zebra", model="ZXP Series 7")
- Tạo product_name_en (English) và product_name_vi (Vietnamese có dấu)
- Tạo synonyms: tên gọi khác, tên kỹ thuật, viết tắt (VD: "printhead" = "đầu in" = "đầu in nhiệt")

### Sub-queries:
- Tạo 5-10 sub_queries tối ưu cho từng platform
- Mỗi query phải phù hợp với platform (EN cho DuckDuckGo, VI cho ecommerce)
- priority=1: gọi đầu tiên, priority=2: gọi tiếp, priority=3: xác minh

## USER QUERY
{query}

## CONTEXT (nếu có)
{context}

## LỊCH SỬ HỘI THOẠI GẦN ĐÂY
{recent_conversation}

## LƯU Ý VỀ FOLLOW-UP
- Nếu query ngắn (<40 ký tự) VÀ lịch sử có tìm kiếm sản phẩm → ĐÂY LÀ FOLLOW-UP
- Ví dụ follow-up: "top 10 đắt nhất", "rẻ nhất ở đâu", "so sánh", "cái nào tốt"
- PHẢI giữ product context từ câu trước: brand, model, category
- VD: Trước "tai nghe Sony WH-1000XM5" → "top 10 đắt nhất" → product_name_vi = "tai nghe Sony WH-1000XM5"
- Sub-queries PHẢI chứa tên sản phẩm gốc + filter mới

Trả về QueryPlan JSON."""


# =============================================================================
# Planner Function
# =============================================================================

async def plan_search_queries(
    query: str,
    context: Optional[dict] = None,
) -> Optional[QueryPlan]:
    """Generate an optimized search plan using LLM LIGHT tier.

    Args:
        query: User's search query (Vietnamese)
        context: Optional conversation context

    Returns:
        QueryPlan if successful, None on any error (graceful degradation)
    """
    try:
        from app.core.config import get_settings
        settings = get_settings()
        if not settings.enable_query_planner:
            return None
    except Exception:
        return None

    try:
        from app.engine.llm_pool import get_llm_light
        llm = get_llm_light()
    except Exception as e:
        logger.debug("[QUERY_PLANNER] LLM init failed: %s", e)
        return None

    # Build context string
    context_str = ""
    recent_turns = ""
    if context:
        conv_history = context.get("conversation_summary", "")
        if conv_history:
            context_str = f"Conversation: {conv_history[:300]}"

        # Sprint 202b: Extract recent turns for follow-up detection
        lc_messages = context.get("langchain_messages", [])
        if lc_messages:
            turn_parts = []
            for msg in lc_messages[-6:]:
                if isinstance(msg, dict):
                    role = msg.get("role", "")
                    content = str(msg.get("content", ""))
                else:
                    role = getattr(msg, "type", "")
                    content = str(getattr(msg, "content", ""))
                if content.strip():
                    # Truncate long AI responses
                    if role in ("ai", "assistant"):
                        content = content[:200]
                    turn_parts.append(f"{role}: {content[:300]}")
            if turn_parts:
                recent_turns = "\n".join(turn_parts[-6:])

    prompt_text = _PLANNER_PROMPT.format(
        query=query,
        context=context_str or "Không có context bổ sung.",
        recent_conversation=recent_turns or "Không có lịch sử.",
    )

    try:
        # Use with_structured_output for reliable JSON parsing
        structured_llm = llm.with_structured_output(QueryPlan)
        plan = await structured_llm.ainvoke(prompt_text)

        if plan and isinstance(plan, QueryPlan):
            # Validate: ensure at least 1 sub-query
            if not plan.sub_queries:
                logger.debug("[QUERY_PLANNER] Plan has no sub_queries, discarding")
                return None
            # Cap sub_queries at 10
            plan.sub_queries = plan.sub_queries[:10]
            # Cap synonyms at 10
            plan.synonyms = plan.synonyms[:10]
            logger.info(
                "[QUERY_PLANNER] Generated plan: intent=%s, strategy=%s, %d sub_queries",
                plan.intent.value,
                plan.search_strategy.value,
                len(plan.sub_queries),
            )
            return plan

        logger.debug("[QUERY_PLANNER] LLM returned non-QueryPlan: %s", type(plan))
        return None

    except Exception as e:
        logger.warning("[QUERY_PLANNER] Planning failed (graceful degradation): %s", e)
        return None


# =============================================================================
# Format for System Prompt Injection
# =============================================================================

def format_plan_for_prompt(plan: QueryPlan) -> str:
    """Convert a QueryPlan into text to inject into the ReAct system prompt.

    Args:
        plan: The generated query plan

    Returns:
        Formatted text string for system prompt injection
    """
    lines = []
    lines.append("## KẾ HOẠCH TÌM KIẾM TỐI ƯU (được tạo bởi Query Planner)")
    lines.append("")
    lines.append(f"**Sản phẩm (EN)**: {plan.product_name_en}")
    lines.append(f"**Sản phẩm (VI)**: {plan.product_name_vi}")
    if plan.brand:
        lines.append(f"**Thương hiệu**: {plan.brand}")
    if plan.model_number:
        lines.append(f"**Model/Mã SP**: {plan.model_number}")
    lines.append(f"**Phân loại**: {plan.intent.value}")
    lines.append(f"**Chiến lược**: {plan.search_strategy.value}")
    lines.append("")

    if plan.synonyms:
        lines.append(f"**Tên gọi khác**: {', '.join(plan.synonyms)}")
        lines.append("")

    if plan.reasoning:
        lines.append(f"**Lý do**: {plan.reasoning}")
        lines.append("")

    # Group sub-queries by priority
    lines.append("### Truy vấn tối ưu theo platform:")
    for priority in [1, 2, 3]:
        queries_at_priority = [sq for sq in plan.sub_queries if sq.priority == priority]
        if queries_at_priority:
            priority_label = {1: "Vòng 1 (ưu tiên)", 2: "Vòng 2 (mở rộng)", 3: "Vòng 3 (xác minh)"}
            lines.append(f"\n**{priority_label.get(priority, f'Vòng {priority}')}**:")
            for sq in queries_at_priority:
                lines.append(f"- **{sq.platform}** [{sq.language}]: `{sq.query}`")

    lines.append("")
    lines.append("**QUAN TRỌNG**: Dùng đúng query đã tối ưu ở trên khi gọi tool. "
                 "Truyền trực tiếp query string vào tham số `search_queries` nếu tool hỗ trợ, "
                 "hoặc dùng làm tham số `product_name`/`query` cho tool.")

    return "\n".join(lines)
